### ISSUE TITLE
OptimumFuse NeoForge Broken

### ISSUE THREAD

**Issue by yellowwinner** [UltimatChamp/optimum-fuse#1]
OptimumFuse 1.3.1 with NeoForge appears to be broken. I gave the log for normal Forge, which does work, for reference.

OptimumFuse 1.3.1-FORGE-MC1.20.1: https://mclo.gs/bsRJMEl
OptimumFuse 1.3.1-NEOFORGE-MC1.20.1: https://mclo.gs/wTzqImc

**Comment by UltimatChamp** [comment]
Seems to be a PrismLauncher issue. I will further investigate it in a day or two (typing this on my phone...). Neoforge is still very young, so, be ready to face these issues with some launchers. :P

I recommend you to use Modrinth Theseus. See <a href="https://github.com/UltimatChamp/optimum-fuse/wiki/Installation#steps">Wiki: Installation</a>!

During my testing, it worked flawlessly on Modrinth Theseus. Besides Theseus, you can try ATLauncher!

**Comment by yellowwinner** [comment]
I ran a VM to try Modrinth and ATLauncher and yeah, it's definitely a Prism issue which is unfortunate because I don't like either of those launchers. Oh well 😅

**Comment by UltimatChamp** [comment]
Nevermind!

**Comment by UltimatChamp** [comment]
Whoops! Wrong issue.
