### ISSUE TITLE
Crash after saving and quiting world [FORGE 1.20.1 - OptimumFuse 1.9.13]

### ISSUE THREAD

**Issue by doemty** [UltimatChamp/optimum-fuse#10]
I have crashes after every quiting and saving world. 
[crash-2024-03-29_21.20.12-client.txt](https://github.com/UltimatChamp/optimum-fuse/files/14807572/crash-2024-03-29_21.20.12-client.txt)
[latest.log](https://github.com/UltimatChamp/optimum-fuse/files/14807574/latest.log)

**Comment by doemty** [comment]
It's strange because the game seems to be saving :/

**Comment by UltimatChamp** [comment]
This is caused by **Seamless Loading Screen**. You can temporarily disable the mod. 
This will be fixed in the next release. Thanks for notifying me!😄

**Comment by doemty** [comment]
> This is caused by **Seamless Loading Screen**. You can temporarily disable the mod. This will be fixed in the next release. Thanks for notifying me!😄

oh! thanks! your modpack is really good! thanks again for fast reply!!

**Comment by UltimatChamp** [comment]
Fixed in [**v1.9.14**](https://modrinth.com/modpack/optimum-fuse/version/1.9.14+forge.1.20.1)!
