### ISSUE TITLE
Don't Clear Chat History

### ISSUE THREAD

**Issue by UltimatChamp** [UltimatChamp/optimum-fuse#13]
### Discussed in https://github.com/UltimatChamp/optimum-fuse/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **doemty** April  7, 2024</sup>
I suggest add mod "Don't Clear Chat History".
As the title says.
https://modrinth.com/mod/dcch</div>

**Comment by UltimatChamp** [comment]
@doemty This should already work in OptimumFuse for Forge _(no use in 1.20.4)_ because of Chat Patches, which restores/saves chat anyway.

**Comment by doemty** [comment]
> @doemty This should already work in OptimumFuse for Forge _(no use in 1.20.4)_ because of Chat Patches, which restores/saves chat anyway.

oh, I think I have not noticed, thanks! <3 (I like your modpack!)

**Comment by UltimatChamp** [comment]
I have a [Discord server](https://discord.gg/kfKjjhv3pn) btw.
Thanks for reporting these issues! <3
