### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kittenvr** [UltimatChamp/optimum-fuse#18]
**Describe the bug**

**To Reproduce**
1 launch

**Expected behavior**
it launch

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - Modpack Version: [1.9.18+forge.1.20.1
**Additional context**
[Add any other context about the problem here.](https://paste.gg/p/anonymous/d8dd04149f7b404bb9f1fd82f2943d00)

**Comment by UltimatChamp** [comment]
**Remove Canary**. There's already Radium installed. Radium and Canary do the same thing but Radium > Canary.
