### ISSUE TITLE
[1.9.18 FABRIC 1.20.4] Resource reload failed bug

### ISSUE THREAD

**Issue by doemty** [UltimatChamp/optimum-fuse#19]
When I try to run Minecraft I meet endless loading game and notification «Resource reload failed»

It happens when I just run Minecraft
![image](https://github.com/UltimatChamp/optimum-fuse/assets/151661389/3b9d0b3f-c0e0-4a26-8107-989324278d76)

**Comment by UltimatChamp** [comment]
I'm unable to reproduce this. 1.20.4 is going to be deprecated anyways. But I'll be happy to help you. Can you send me your latest log file?

**Comment by doemty** [comment]
> I'm unable to reproduce this. 1.20.4 is going to be deprecated anyways. But I'll be happy to help you. Can you send me your latest log file?

Sure
[latest.log](https://github.com/UltimatChamp/optimum-fuse/files/15212619/latest.log)

**Comment by UltimatChamp** [comment]
Hmm... Which _(extra)_ resource-packs are you using?

**Comment by doemty** [comment]
> Hmm... Which _(extra)_ resource-packs are you using?

No one. I have just deleted any resorce packs and launched game. Still the same problem.
![image](https://github.com/UltimatChamp/optimum-fuse/assets/151661389/13814bc3-86cc-4ebd-9fee-e7202c2221b2)
[latest.log](https://github.com/UltimatChamp/optimum-fuse/files/15212905/latest.log)

**Comment by doemty** [comment]
> > Hmm... Which _(extra)_ resource-packs are you using?
> 
> No one. I have just deleted any resource packs and launched game. Still the same problem. ![image](https://private-user-images.githubusercontent.com/151661389/328016511-13814bc3-86cc-4ebd-9fee-e7202c2221b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NDg0NDcsIm5iZiI6MTcxNDk0ODE0NywicGF0aCI6Ii8xNTE2NjEzODkvMzI4MDE2NTExLTEzODE0YmMzLTg2Y2MtNGViZC05ZmVlLWU3MjAyYzIyMjFiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQyMjI5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWQ5OWFjNTJiMDNiYTVlNzc2YzcwMzA3MmUyYzQxMjAyMzRlOGE4MTkzNmJiYjVjODI1OWVmZjY0NTk0OGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.quCsW0kCBVAwMglA4bzNTcDuuUtHIRQwGYA-u-CXPdc) [latest.log](https://github.com/UltimatChamp/optimum-fuse/files/15212905/latest.log)

Nevermind. I have troubles exactly in 1.20.4 Minecraft version. There is nothing wrong in your modpack. Sorry <3
