### ISSUE TITLE
Water flickering

### ISSUE THREAD

**Issue by PabuUwU** [UltimatChamp/optimum-fuse#22]
The water flickers when viewed from certain positions or angles.

https://modrinth.com/modpack/optimum-fuse/version/1.10.0-rc.11+forge.1.20.1

To reproduce this issue, find a river or the sea and change your position and camera angle until you see the flickering (this also happens with ice).

The only way i know to fix it is to remove oculus but i want to use shaders ):

Here is a video showing the same bug with a different mod pack:
[Video Link](https://www.youtube.com/watch?v=Ra3iLBlx93Q)

**Comment by UltimatChamp** [comment]
Try updating Embeddium.

**Comment by PabuUwU** [comment]
still happens

https://www.youtube.com/watch?v=Lbn92C8TGCo

**Comment by PabuUwU** [comment]
I was testing various configurations, so I only put these mods in the mods folder:

- embeddium-0.3.19+mc1.20.1-all.jar
- fabric-api-0.92.1+1.11.8+1.20.1.jar
- lazurite-1.0.4+mc1.20.1.jar
- oculus-mc1.20.1-1.7.0.jar
- ConnectorExtras-1.10.1+1.20.1.jar
- continuity-3.0.0-beta4+1.20.1.jar
- fabric-language-kotlin-1.11.0+kotlind.2.0.0.jar
- Connector-1.0.0-beta43+1.20.1.jar

It looks like with this configuration, the flickering water glitch is not occurring. I tried adding the other mods in the modpack, but I couldn't find which mod is causing the glitch. The only thing I know is that Oculus and Lazurite (Embeddium) are not the problem.

I don't know, I really want to use shaders ):

**Comment by UltimatChamp** [comment]
Try [`1.11.1+neo.1.21`](https://modrinth.com/modpack/optimum-fuse/version/1.11.1+neo.1.21)!
