### ISSUE TITLE
Crash when try to configure mod in menu (Catalogue I think)

### ISSUE THREAD

**Issue by doemty** [UltimatChamp/optimum-fuse#24]
It just crashes every time I try to configure mod

To Reproduce
1. Just try to configure mod

Maybe it is only my problem? 
Also I feel a little guilty because a lot of the questions and discussions were done by me, srry<3

**Comment by UltimatChamp** [comment]
> Maybe it is only my problem?
Also I feel a little guilty because a lot of the questions and discussions were done by me, srry<3

No problem!

**Comment by UltimatChamp** [comment]
> Just try to configure mod

The pack is archived, you should use my other modpack, [**FlawlesslyOptimized**](https://www.curseforge.com/minecraft/modpacks/flawlesslyoptimized)

**Comment by doemty** [comment]
Oh, I didn't even know, Thanks

**Comment by doemty** [comment]
> > The pack is archived, you should use my other modpack, [**FlawlesslyOptimized**](https://www.curseforge.com/minecraft/modpacks/flawlesslyoptimized)

Sorry, but can I ask about why is it archived? Hon I really liked this pack, it has good perfomance and visual improvements as I like. As I think second part is missing in FlawlesslyOptimized (no hate or negative, bro). Still your folowwer tho <3 
P.S.: sorry for annoying you 🙏

**Comment by UltimatChamp** [comment]
@doemty **OptimumFuse** is back! Releasing a **NeoForge** for **1.21** version shortly!

**Comment by doemty** [comment]
> @doemty **OptimumFuse** is back! Releasing a **NeoForge** for **1.21** version shortly!

Oh glad to hear! Honestly. Maybe inappropriate question, but will you continue for Forge 1.20.1? And one more question. Why have you stopped working on OptimumFuse? And then have started again. Despite everything glad cause of you're back <3
