### ISSUE TITLE
Sodium Shadowy Path Blocks

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#25]
### Modrinth link

https://modrinth.com/mod/sodium-shadowy-path-blocks

### Source link

https://github.com/Rynnavinx/sodium-shadowy-path-blocks

### License

GNU LGPLv3

### Mod description

An addon for Sodium that reintroduces smooth lighting to dirt paths.

### Why should it be in the modpack?

• Most users are used to the shadowyness of the vanilla dirt path and this mod reintroduces it.
• Actively Updated
• Can be disabled in settings if the user doesn't like the mod.

### Why shouldn't it be in the modpack?

• It could be incompatible with a mod within the modpack.

### Additional details

• It's incompatible on minecraft versions before 1.19
• Only works when Smooth Lighting is enabled.

**Comment by UltimatChamp** [comment]
Will be added in the next release. 👍
