### ISSUE TITLE
Better Statistics Screen

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#26]
### Modrinth link

https://modrinth.com/mod/better-stats

### Source link

https://github.com/TheCSMods/mc-better-stats

### License

LGPL-3.0

### Mod description

Better Statistics Screen enhances Minecraft's stats tracking, offering detailed and customizable data on player activities like kills and resource collection, with an improved interface for easier viewing.

### Why should it be in the modpack?

• Detailed Statistics: The mod provides enhanced stats and data about the player's game, such as detailed kill counts, resource gathering, and more.
• Actively Updated
• Better Interface: It improves the user interface for viewing stats, making it easier to understand and interact with the data.

### Why shouldn't it be in the modpack?

• Over-Informative: For some players, having too much detailed statistical information might detract from the immersion or challenge of the game. If the mod provides too much data, it could potentially disrupt the balance or enjoyment of the game.
• Conflicts: The mod might have compatibility issues with other mods in the modpack.

**Comment by UltimatChamp** [comment]
Closing this as "Not Planned" due to the mod being too detailed, and not vanilla-styled.
