### ISSUE TITLE
Gamma Utils(Fullbright)

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#27]
### Modrinth link

https://modrinth.com/mod/gamma-utils/versions

### Source link

https://github.com/Sjouwer/gamma-utils

### License

LGPL-3.0

### Mod description

It's a fullbright mod for clients.

### Why should it be in the modpack?

• Highly Customizable
• Actively Updated
• Rather then using a full bright texture pack this mod allows the user to change the gamma to their liking.

### Why shouldn't it be in the modpack?

• Some players would say: This mod is a kind of cheat.
• Most users wouldn't even know if the mod was installed, as the settings for the mod are in the mod menu.

### Additional details

There is a issue with Ryaomic Lights mod.
https://github.com/ThinkingStudios/RyoamicLights/issues/11

**Comment by UltimatChamp** [comment]
> Some players would say: This mod is a kind of cheat.

Yeah, I don't think **FullBright** _(or any xray, etc feature)_ is a good idea for the pack.
Closing this issue as "Not Planned".
