### ISSUE TITLE
Respackopts

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#28]
### Modrinth link

https://modrinth.com/mod/respackopts

### Source link

https://git.frohnmeyer-wds.de/JfMods/Respackopts

### License

MIT

### Mod description

Respackopts provides resource and data packs with config menus.
By default, it provides a custom system for conditional resources, resource expansion and integrates with frex, canvas and fabulous shaders

### Why should it be in the modpack?

• It enables users to configure their resource packs.

### Why shouldn't it be in the modpack?

• There are only a handful amount of texture packs that can utilize this mod.
• The mod increases the resource reloading time and in game loading times.

**Comment by UltimatChamp** [comment]
I think it is wise to add the mod only when a resource-pack in the modpack actually supports it, since, there are only a handful of resource-packs that actually use it.
