### ISSUE TITLE
Faster Random

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#29]
### Modrinth link

https://modrinth.com/mod/faster-random

### Source link

https://github.com/AnOpenSauceDev/FastRandom

### License

Apache 2.0

### Mod description

Faster Random is a rewrite of Minecraft's random systems to use the new LXM generators introduced in Java 17, instead of the slower CheckedRandom (and related generators) within Minecraft.

### Why should it be in the modpack?

• Since this modpack improves the game's performance and visuals I thought this could be a great addition.

### Why shouldn't it be in the modpack?

• I dont know much about this mod just found it randomly and there seems to be a issue so it should be researched before adding to the modpack.

### Additional details

Like I said the mod should be checked to see if it's worth adding to the modpack since there could be some problems.

**Comment by UltimatChamp** [comment]
Closing this as "Not Planned" because this mod breaks vanilla-parity, by altering vanilla cave generation.

**Comment by MissionWAR** [comment]
Thank you for your response. I understand that the mod alters vanilla cave generation. However, the mod description states: "Optifine's math optimizations do far more damaging changes to worldgen than Faster Random." If this mod significantly improves world generation or FPS, I believe it could still be a valuable addition. Given that the changes to cave generation may be subtle and not easily noticeable, it might be worth reconsidering the inclusion of this mod. I appreciate your consideration of this perspective.
