### ISSUE TITLE
Thread Tweak

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#31]
### Modrinth link

https://modrinth.com/mod/threadtweak

### Source link

https://github.com/skywardmc/threadtweak

### License

MIT

### Mod description

ThreadTweak lets you improve and tweak Minecraft CPU scheduling. It is a maintained version of the [original Smooth Boot mod](https://github.com/UltimateBoomer/mc-smoothboot), allowing you to still change CPU thread priorities in-game.

### Why should it be in the modpack?

• It could be a great addition to the modpack for increased performance.

### Why shouldn't it be in the modpack?

• Could be incompatible with the other optimization mods.

### Additional details

Although I noticed that this mod has over a million downloads, I thought it might be worth bringing to your attention in case you haven’t seen it yet.

**Comment by UltimatChamp** [comment]
**ModernFix** already does this by default. The only reason you need this mod is to tweak _thread priorities_ to be more suitable for your setup, or experimenting some _unstable_ configurations...
