### ISSUE TITLE
NeoForge Crash

### ISSUE THREAD

**Issue by ReinhardTristanHeydrich** [UltimatChamp/optimum-fuse#32]
### Describe your issue

The first time I started the ModPack, everything went well, I created and entered a world, until my game simply crashed when I tried to break a leaf.
The bug comes from an incompatibility between the "Cull Less Leaves" and "Sodium".

After the crash, I try to enter the modpack again, and the game crashes on the title screen.
The crash is caused by the “Better Mod Menu” mod. When I disable this mod in the laucher, the game doesn't crash on the title screen like before.

The way I managed to find out which mod the error was from was because I sent the file to ChatGPT, and his answers were correct in both cases, I disabled the mods, and the crashes stopped happening. They weren't exactly the same as the logs I sent in this Bug Report, but the reasons for the crashes were the same.

My suggestion is to replace the “Better Mod Menu” with the “Catalogue” mod if possible. In my tests, Catalogue was much more stable at not crashing in the title menu than Better Mod Menu.
(In my test, I used "[Forge Config API Port](https://modrinth.com/mod/forge-config-api-port)" with Catalogue)

### Modpack version

OptimumFuse 1.12.0+neo.1.21.1

### Launcher

PollyMC

### Additional context

First time Entering ModPack (Cull Less Leaves): https://mclo.gs/YVZaBts
Second time Entering ModPack (Better Mod Menu): https://mclo.gs/ljpIPft

**Comment by UltimatChamp** [comment]
I'll release a fix version soon. Thanks for informing me!
