### ISSUE TITLE
Mod Menu Crash

### ISSUE THREAD

**Issue by viidsn** [UltimatChamp/optimum-fuse#39]
### Describe your issue

Game crashes when pressing "Configure" button in Mod Menu for some mods.

- Zoomify
- Adaptive Tooltips
- Chat Patches
- Debugify
- Flow

I also had a crash when pressed "GUI Sounds" button while cofigurating mod "Sounds".

I think there is more, but i didn't managed to check them all.

### Modpack version

1.10.0-rc.11+forge.1.20.1

### Launcher

Modrinth

**Comment by UltimatChamp** [comment]
1.20.1 isn't actually supported by the modpack anymore. You should now switch to the **NeoForge 1.21.1** version.
Nonetheless, I think you can fix this issue by replacing the **Forge** version of **YACL** there, with the [**Fabric** version](https://modrinth.com/mod/yacl/version/3.5.0+1.20.1-fabric).

**Comment by viidsn** [comment]
> 1.20.1 isn't actually supported by the modpack anymore. You should now switch to the **NeoForge 1.21.1** version. Nonetheless, I think you can fix this issue by replacing the **Forge** version of **YACL** there, with the [**Fabric** version](https://modrinth.com/mod/yacl/version/3.5.0+1.20.1-fabric).

https://i.imgur.com/MblQ4MY.png

Minecraft for some reason see a wrong version of YACL.

**Comment by viidsn** [comment]
> Minecraft for some reason see a wrong version of YACL.

I fixed it somehow, but it still crashes

**Comment by UltimatChamp** [comment]
Can you provide logs? (upload `latest.log` to https://mclo.gs)

**Comment by UltimatChamp** [comment]
Closing this as "Won't Fix" as there's been no response, and 1.20.1 for **Forge** isn't officially supported/maintained anymore.
