### ISSUE TITLE
Minecraft Chat is Offset

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#40]
### Describe your issue

I'm not sure if this issue is specific to me or if it affects everyone, but the Minecraft chat appears to be offset. When I try to click on a location to teleport, the game doesn't copy the coordinates as expected; instead, it copies a different message.

### Modpack version

OptimumFuse 1.12.6+fabric.1.21.1

### Launcher

Modrinth

### Additional context

https://github.com/user-attachments/assets/e7235510-18be-45a8-801d-3acc2642b30d

**Comment by UltimatChamp** [comment]
Can't reproduce this issue (now).
