### ISSUE TITLE
Mob Plaques

### ISSUE THREAD

**Issue by MissionWAR** [UltimatChamp/optimum-fuse#45]
### Modrinth link

https://modrinth.com/mod/mob-plaques

### Source link

https://github.com/Fuzss/mobplaques

### License

MPL-2.0

### Mod description

Mob Plaques is a mod that adds small displays above a mob's name tag to show its current health. It also displays armor points, armor toughness, and air supply when applicable. The mod includes various configuration options, allowing you to customize the plaques to your preference.

### Why should it be in the modpack?

It's a really useful mod that can be fully configured. Additionally, it's unobtrusive and fits well with the vanilla aesthetic.

### Why shouldn't it be in the modpack?

Some players might not appreciate this feature.

### Additional details

There are other mods that do the same job as this one, but I think this one is better.

**Comment by UltimatChamp** [comment]
Closing this as "Not Planned". I don't think this mod fits the **vanilla** focus of the modpack.
