### ISSUE TITLE
Remove Switcheroo

### ISSUE THREAD

**Issue by han-tyumi** [UltimatChamp/optimum-fuse#6]
**Modrinth Link:** https://modrinth.com/mod/switcheroo
**Source Link:** https://github.com/NatoBoram/switcheroo

**Why this should mod not be included?**
I haven't played around with it too much, but I was finding Switcheroo quite wonky at least with a controller out of the box.
I also feel like this one could be cut if the direction of this pack is to stay rather light.
It seems it may be polarizing between players in terms of if they like it or not.

**Additional context**
I'll look into getting a video of the wonkiness, but it looks like it might be a pain to capture on a Steam Deck.

**Comment by UltimatChamp** [comment]
Can you explain how to reproduce the wonkiness?
Also, can you try using [AutoSwitch](https://modrinth.com/mod/autoswitch) and [AutoTools](https://modrinth.com/mod/minecraft_autotools)?

**Comment by han-tyumi** [comment]
I haven't been able to get around to this yet, but I thought I'd give some more info.

I believe what I was experiencing was that when swapping tools to mine say some netherack with a max efficiency diamond pick, I would sometimes experience that the block would break and other times it would not.
So this would make switching between placing blocks and mining a bit unpredictable when trying to do things efficiently and would lead to me mining extra blocks unintentionally.

I believe I saw the same with a max efficiency shovel as well.

**Comment by UltimatChamp** [comment]
Try [AutoTools](https://modrinth.com/mod/minecraft_autotools). It seems much polished than Switcheroo, and seems to be more configurable.

Make sure to toggle it first, through Mod Menu, and turn on Switch back in config.

```css
toggle: true, 
switchBack: true
```
