### ISSUE TITLE
[1.20.1][NeoForge/Forge] CIT broken

### ISSUE THREAD

**Issue by HowardZHY** [UltimatChamp/optimum-fuse#8]
**Describe the bug**
although there's CIT Resewn mod, but seems none of the CIT texture from any CIT RP are acturally loaded

**To Reproduce**
1. Add any RP with CIT
2. CIT Textures won't work

**Setup (please complete the following information):**
 - OS: [Win11]
 - Modpack Version: [1.9.5+neo.1.20.1]

**Additional context**
If you can't reproduce then maybe I break something, apologize if it's invalid

**Comment by UltimatChamp** [comment]
Thanks for letting me know😅! I'm pretty sure, CIT worked before on (Neo)Forge. This will be fixed by **Sinytra Connector** team. See https://github.com/Sinytra/Connector/issues/820. The mod will be _temporarily, removed_.

**Comment by UltimatChamp** [comment]
CIT Resewn will be temporarily replaced with ForgeCIT, in `1.9.7` to fix this issue!
